import type { Coordinate } from '../types'
import type { AttackItemId, DefenseItemId } from './items'

export type BoardItem = {
  id: DefenseItemId | AttackItemId
  position: Coordinate
}
export const BOARD_ITEMS: BoardItem[] = [
  // Row 1
  { id: 'certificate', position: [1, 0] },
  { id: 'usb-stick', position: [1, 0] },
  { id: 'virus', position: [3, 0] },
  { id: 'binoculars', position: [3, 0] },
  { id: 'lock', position: [4, 0] },
  { id: 'data-exchange', position: [4, 0] },
  { id: 'gps-tracker', position: [5, 0] },
  { id: 'fake-identity-card', position: [5, 0] },
  { id: 'encrypted-data', position: [6, 0] },
  { id: 'dynamite', position: [6, 0] },
  { id: 'license', position: [7, 0] },
  { id: 'tools', position: [7, 0] },
  { id: 'security-camera', position: [8, 0] },
  { id: 'cloud', position: [8, 0] },
  // Row 2
  { id: 'security-camera', position: [0, 1] },
  { id: 'fake-identity-card', position: [0, 1] },
  { id: 'alarm-system', position: [1, 1] },
  { id: 'data-exchange', position: [1, 1] },
  { id: 'gun', position: [2, 1] },
  { id: 'blueprint', position: [2, 1] },
  { id: 'extinguisher', position: [3, 1] },
  { id: 'cloud', position: [3, 1] },
  { id: 'usb-stick', position: [6, 1] },
  { id: 'blueprint', position: [6, 1] },
  { id: 'lock', position: [8, 1] },
  { id: 'virus', position: [8, 1] },
  // Row 3
  { id: 'insurance', position: [0, 2] },
  { id: 'tools', position: [0, 2] },
  { id: 'security-camera', position: [2, 2] },
  { id: 'dynamite', position: [2, 2] },
  { id: 'license', position: [3, 2] },
  { id: 'usb-stick', position: [3, 2] },
  { id: 'digital-footprint', position: [4, 2] },
  { id: 'virus', position: [4, 2] },
  { id: 'encrypted-data', position: [5, 2] },
  { id: 'binoculars', position: [5, 2] },
  { id: 'security-camera', position: [6, 2] },
  { id: 'fake-identity-card', position: [6, 2] },
  { id: 'firewall', position: [7, 2] },
  { id: 'data-exchange', position: [7, 2] },
  { id: 'gun', position: [8, 2] },
  { id: 'dynamite', position: [8, 2] },
  // Row 4
  { id: 'virus', position: [0, 3] },
  { id: 'blueprint', position: [0, 3] },
  { id: 'data-exchange', position: [3, 3] },
  { id: 'insurance', position: [3, 3] },
  { id: 'cloud', position: [5, 3] },
  { id: 'alarm-system', position: [5, 3] },
  { id: 'tools', position: [6, 3] },
  { id: 'extinguisher', position: [6, 3] },
  { id: 'binoculars', position: [7, 3] },
  { id: 'digital-footprint', position: [7, 3] },
  // Row 5
  { id: 'digital-footprint', position: [1, 4] },
  { id: 'gun', position: [1, 4] },
  { id: 'lock', position: [2, 4] },
  { id: 'dynamite', position: [2, 4] },
  { id: 'tools', position: [3, 4] },
  { id: 'binoculars', position: [3, 4] },
  { id: 'gun', position: [4, 4] },
  { id: 'firewall', position: [4, 4] },
  { id: 'usb-stick', position: [5, 4] },
  { id: 'gps-tracker', position: [5, 4] },
  { id: 'data-exchange', position: [6, 4] },
  { id: 'insurance', position: [6, 4] },
  { id: 'blueprint', position: [8, 4] },
  { id: 'license', position: [8, 4] },
  // Row 6
  { id: 'usb-stick', position: [0, 5] },
  { id: 'blueprint', position: [0, 5] },
  { id: 'alarm-system', position: [1, 5] },
  { id: 'cloud', position: [1, 5] },
  { id: 'extinguisher', position: [2, 5] },
  { id: 'virus', position: [2, 5] },
  { id: 'fake-identity-card', position: [3, 5] },
  { id: 'certificate', position: [3, 5] },
  { id: 'blueprint', position: [5, 5] },
  { id: 'cloud', position: [5, 5] },
  { id: 'lock', position: [6, 5] },
  { id: 'virus', position: [6, 5] },
  { id: 'encrypted-data', position: [7, 5] },
  { id: 'dynamite', position: [7, 5] },
  { id: 'fake-identity-card', position: [8, 5] },
  { id: 'cloud', position: [8, 5] },
  // Row 7
  { id: 'binoculars', position: [0, 6] },
  { id: 'license', position: [0, 6] },
  { id: 'usb-stick', position: [2, 6] },
  { id: 'gun', position: [2, 6] },
  { id: 'digital-footprint', position: [4, 6] },
  { id: 'dynamite', position: [4, 6] },
  { id: 'certificate', position: [7, 6] },
  { id: 'binoculars', position: [7, 6] },
  { id: 'extinguisher', position: [8, 6] },
  { id: 'gun', position: [8, 6] },
  // Row 8
  { id: 'data-exchange', position: [0, 7] },
  { id: 'gun', position: [0, 7] },
  { id: 'gps-tracker', position: [1, 7] },
  { id: 'tools', position: [1, 7] },
  { id: 'firewall', position: [2, 7] },
  { id: 'fake-identity-card', position: [2, 7] },
  { id: 'virus', position: [3, 7] },
  { id: 'binoculars', position: [3, 7] },
  { id: 'encrypted-data', position: [4, 7] },
  { id: 'usb-stick', position: [4, 7] },
  { id: 'dynamite', position: [6, 7] },
  { id: 'tools', position: [6, 7] },
  { id: 'cloud', position: [7, 7] },
  { id: 'alarm-system', position: [7, 7] },
  { id: 'blueprint', position: [8, 7] },
  { id: 'insurance', position: [8, 7] },
]
